crop:
  enabled: false
  scale: [0.80, 1.0]
  ratio: [0.9, 1.1]

flip:
  enabled: false
  horizontal: false
  vertical: false

rotate:
  enabled: false
  degrees: 20

affine:
  enabled: false
  degrees: 0
  translate: [0.05, 0.05]
  scale: [0.95, 1.05]
  shear: 5

color:
  enabled: false
  brightness: 0.1
  contrast: 0.1
  saturation: 0.05
  hue: 0.02

cutout:
  enabled: false
  p: 0.25
  scale: [0.02, 0.10]
  ratio: [0.3, 3.3]

normalize:
  mean: [0.485, 0.456, 0.406]
  std: [0.229, 0.224, 0.225]
